### ISSUE TITLE
reset all adapters

### ISSUE THREAD

**Issue by henrikx** [serock/pla-util#1]
Currently it seems like reset command only resets the local adapter and not the remote adapter. Would be nice if you could add support for that.

**Comment by henrikx** [comment]
If needed I can provide a packet capture of the Tenda PH3 configurator program doing this.

**Comment by serock** [comment]
If you would attach a packet capture, that would be helpful.

**Comment by henrikx** [comment]
Sorry for taking a while to provide this.
Here is the packet dump of me resetting the remote adapter

[dump.zip](https://github.com/serock/pla-util/files/4113455/dump.zip)

To be honest all I want to do is to use this in a script to automatically reboot the adapter. Reset does it, but also deletes all settings. Do you think that it would be possible?

The reason being that the adapter randomly loses link on the router side, where the only way to fix it is to "replug" the ethernet either by physcially reconnecting it, restarting the router or restarting the adapter.

**Comment by serock** [comment]
Thank you for the packet dump. I'll have to see if I can get a factory reset to work for a remote adapter.

I think it should be possible to reboot an adapter because it looks like there's a restart command available in the utilities for the D-Link adapter.

**Comment by henrikx** [comment]
Thanks. Would be very nice if you could implement a reboot function too!
Could you link me the D-Link software? I could not find it.

I tried the TP-link configurator for an equivalent adapter which uses the same protocol. Surprisingly it detected the adapters, but wouldn't let me do much with them because it didn't recognize the model.

**Comment by serock** [comment]
On the [https://support.dlink.com/ProductInfo.aspx?m=DHP-701AV](https://support.dlink.com/ProductInfo.aspx?m=DHP-701AV) page, there are downloads for  "PLC Utility for Windows (5.02B02)" and "PLC Utility Lite (1.01 - WIN)".

**Comment by henrikx** [comment]
Thanks for the link.

Both tools show the adapters, and lets me change it's name and factory reset, but it doesn't look like it has the option to restart it.

Maybe it hides thoese options because the program does not recognize the models, but I'm sure the adapters would respond to the commands according to protocol.

I may have solved the lost link issue though. At first I used static DHCP on the router to assign an IP to the server, but now I set the server to use static IP without DHCP and it has been stable ever since. Requires more testing though.

**Comment by serock** [comment]
One of the utilities (I think it was the "Lite" one) came with a l2command.exe that you can run from a Windows Command Prompt. If you run l2command.exe without providing any command line arguments, it might print usage info because I have a list of commands including:

Usage: l2command.exe NIC_mac_address apcm_sta_restart

**Comment by henrikx** [comment]
Thanks, that worked for restarting the adapter with command 

`l2command.exe ethernet-mac apcm_sta_restart -m plc-mac`

plc mac can be found by running 

`l2command.exe ethernet-mac discover_list`

Still need this to run on Linux. Might work with Wine, but I would be very thankful if you could implement reboot into your program.

Edit:
Just saw that you implemented a reboot function which is very nice. Just need the option to specify the target mac address.

**Comment by henrikx** [comment]
It is interesting. That tool can change a whole bunch of advanced settings. Too bad I couldn't find a good documentation of what each setting do and what parameters are valid.

**Comment by serock** [comment]
I uploaded a new release. It has a restart command and reset command; you can specify the MAC address for both commands. Please let me know if you find any issues.

**Comment by henrikx** [comment]
Thanks!
Implemented it now on my server with the following script to workaround my original issue:

```bash
#!/bin/bash
if ping -q -c 2 -W 1 192.168.0.1 >/dev/null; then
  echo "IPv4 is up"
else
  echo "IPv4 is down. Attempting adapter reset"
  if pla-util vmbr0 restart b8:3a:08:a8:b5:04; then
    echo "Adapter reset successful"
  else
    echo "Could not send command to PLC"
    exit 1
  fi
fi
```
and then running it with a systemd timer.
