### ISSUE TITLE
libcap2 support

### ISSUE THREAD

**Issue by smartbyte** [serock/pla-util#11]
Hi,

any chance, you could compile the binary package with libcap2 support?
I am on Ubuntu 23.04 and cannot install libcap1 anymore. :-(

Kind regards,

**Comment by serock** [comment]
Hello @smartbyte,

I tried running the existing 2.0.0 binaries in a Docker container with  the ubuntu 23.04 image. I installed the **libpcap-dev** and **libcap2-bin** packages. The only issue I had was with libpcap: I had to create a symbolic link named `libpcap.so.1`. I didn't see any issues with libcap2.

For reference, here's the list of commands I used to test the pla-util binary on ubuntu 23.04:

```
apt update
apt install libpcap-dev libcap2-bin wget
cd /usr/lib/x86_64-linux-gnu/
ln -s libpcap.so.1.10.3 libpcap.so.1
cd /root
mkdir bin
cd bin
wget https://github.com/serock/pla-util/releases/download/2.0.0/pla-util-2.0.0-x86-64-linux-bin.tar.gz
tar xvzf pla-util-2.0.0-x86-64-linux-bin.tar 
./pla-util discover
```

If the above info doesn't help, would you please share any error messages you're seeing?

Thanks.

**Comment by smartbyte** [comment]
Shame on me! That is so embarrassing...

I have only read libcap and not lib!p!cap! I tried everything to install libcap version 1, without realising that there are two libraries libcap2 and libpcap1.

Thanks for the help and the detailed manual on how to do it.

It works now!

AWESOME TOOL!: 
./pla-util -i eth0 -p "94:18:65:12:34:56" get-network-stats
Number of stations: 1
Station 1:
  Destination Address (DA):  94:18:65:65:43:21
  Avg PHY Data Rate to DA:   164 Mbps
  Avg PHY Data Rate from DA: 249 Mbps

That was exactly what I was looking for. Thanks for the effort of writing this tool! It really makes  a difference in my life!

**Comment by serock** [comment]
I'm glad that the tool is working for you.
