### ISSUE TITLE
Update supported devices list in Readme.md

### ISSUE THREAD

**Issue by henrikx** [serock/pla-util#2]
Tenda PH3 can be controlled with this program.

**Comment by serock** [comment]
Thank you for reporting that the program works with the Tenda PH3. I updated the Readme.md.

**Comment by henrikx** [comment]
Thanks

**Comment by RubberDucky007** [comment]
I've got a response with this tool from my TL-PA9020 Adapters under Ubuntu 18 64-bit. But the Answers are not what i expected.

**Comment by serock** [comment]
@RubberDucky007, you can open a new issue and explain what you see in the response and what you expected to see.

**Comment by RubberDucky007** [comment]
> @RubberDucky007, you can open a new issue and explain what you see in the response and what you expected to see.

All i want to say here is: seems to work with TL-PA9020 too. But: Feature-request. :)  #7 Done.
