### ISSUE TITLE
power_line_adapter-network.adb:63 range check failed

### ISSUE THREAD

**Issue by flarn2006** [serock/pla-util#4]
I'm getting the following error:

```
# pla-util enp6s0 discover

Execution of pla-util terminated by unhandled exception
raised CONSTRAINT_ERROR : power_line_adapter-network.adb:63 range check failed
Call stack traceback locations:
0x421fb1 0x42294b 0x425598 0x4285d6 0x403919 0x403f62 0x7f48d72dab23 0x403838 0xfffffffffffffffe

# pla-util enp6s0 get-network-info any

Execution of pla-util terminated by unhandled exception
raised CONSTRAINT_ERROR : power_line_adapter-network.adb:63 range check failed
Call stack traceback locations:
0x421fb1 0x423272 0x426741 0x42870e 0x403919 0x403f62 0x7f758b7c7b23 0x403838 0xfffffffffffffffe
```

I looked in Wireshark, and I do see that it sends out an Ethernet broadcast packet with protocol 0x8912, and then my Powerline adapters respond with similar packets. So the crash must be happening at some point after it sends the packet, but before it actually displays the results.

**Comment by serock** [comment]
I haven't been able to reproduce this issue. Can you provide screenshots of Wireshark showing the details of the response packets or a packet capture file with the 0x8912 protocol packets?

**Comment by flarn2006** [comment]
[Here's one I just took.](https://github.com/serock/pla-util/files/6672216/discover.zip) The adapter in question wasn't communicating properly with the others at the time, so I only got the response from that one, but it was still enough to cause the crash.

Here's the command line and output from that test:
```
$ sudo pla-util enp6s0 discover

Execution of pla-util terminated by unhandled exception
raised CONSTRAINT_ERROR : power_line_adapter-network.adb:63 range check failed
Call stack traceback locations:
0x421fb1 0x42294b 0x425598 0x4285d6 0x403919 0x403f62 0x7fc98ee44b23 0x403838 0xfffffffffffffffe
```

**Comment by serock** [comment]
Thanks for reporting the issue.

I pushed a fix to the master branch, or if you want to test a binary, you can try this:
[pla-util.gz](https://github.com/serock/pla-util/files/6672774/pla-util.gz)

Please let me know whether the fix works for you.

**Comment by flarn2006** [comment]
Yep, looks like it works now. Thanks for the fix!
