### ISSUE TITLE
Only Intel(ish) devices?

### ISSUE THREAD

**Issue by mcccol** [serock/pla-util#6]
The Readme specifies that this program is intended only for Intel Linux. It isn't clear to me why this should be so. Could you please explain the limitation?

**Comment by serock** [comment]
All of my development systems are Intel x86-64 systems. So I have tested the program only on Intel-based systems. It's possible that the program works on other processor architectures, like ARM or RISC-V, but I haven't tried that.

**Comment by mcccol** [comment]
I just successfully compiled and ran the current version on a raspberry pi 4. Thanks for putting in the hard yards, and thanks for your program!

**Comment by serock** [comment]
That's great news that you got the program working on the raspberry pi 4! Thanks for letting me know.

**Comment by serock** [comment]
The README was updated to not say that the program is only for x86-64 machines.
