### ISSUE TITLE
What i need is the transferrate between two adapters.

### ISSUE THREAD

**Issue by RubberDucky007** [serock/pla-util#7]
It seems my TL-PA9020 adapters work.

> sudo ./pla-util enp0s25 discover
> c0:25:e9:xx:xx:1c tpver_902011_161009_902
> c0:25:e9:xx:xx:14 tpver_902011_161009_902

and

> sudo ./pla-util enp0s25 get-network-info any
> Number of networks: 1
> Network 1:
>   NID:                             xxxxxxxxxxxxxxx
>   SNID:                            5
>   TEI:                             63
>   CCo MAC Address:                 c0:25:e9:xx:xx:1c
>   Backup CCo MAC Address:          00:00:00:00:00:00
>   Number of Coordinating Networks: 0
>   Station Role:                    CCO
>   Network Kind:                    IN_HOME_NETWORK
>   Status:                          JOINED
> 

But the information that i really wish to get from it is the transfer-rate between these two adapters. Is there an option or a chance to get it?

The Windows tpPLC tool from TP-Link shows it with a line between the adapters shown in the programm window. So i believe there must be a value one can read out.

**Comment by serock** [comment]
I can add a command to return both the average transmit data rate and the average receive data rate. D-Link's utility sounds similar to TP-Link's utility. The D-Link utility shows a single data rate between my two adapters, which happens to be the average receive data rate.

**Comment by stn-stn** [comment]
I'd also like this feature. I recently migrated my PLC networks from TL-PA4010 and TL-PA8010 adapters to TL-PA7017 adapters which are apparenlty not suported by the [open-plc-utils](https://github.com/qca/open-plc-utils) because of using Broadcom chipsets instead of Qualcomm Atheros. I found this pla-util instead and it seems to be able to communicate with the TL-PA7017 fine, but I really miss the information about the transmit/receive rate between two given MACs.

```
$ pla-util eth0 discover
c0:06:c3:xx:xx:60 tpver_701F14_191101_901
c0:06:c3:xx:xx:ec tpver_701F14_191101_901

$ pla-util eth0 get-network-info any
Number of networks: 1
Network 1:
  NID:                             0767ff53xxxx5e (SL-HS)
  SNID:                            13
  TEI:                             3
  CCo MAC Address:                 34:e8:94:xx:xx:71
  Backup CCo MAC Address:          c0:06:c3:ee:ee:ec
  Number of Coordinating Networks: 0
  Station Role:                    STA
  Network Kind:                    IN_HOME_NETWORK
  Status:                          JOINED
```

**Comment by serock** [comment]
I added a `get-network-stats` command that provides data rates:

```
Number of stations: 1
Station 1:
  Destination Address (DA):  c4:12:f5:xx:xx:xx
  Avg PHY Data Rate to DA:   382 Mbps
  Avg PHY Data Rate from DA: 394 Mbps
```

There's a new 1.1.0 release available with this change.

**Comment by stn-stn** [comment]
Thanks! Unfortunately it didn't work for me though :-(

```
$ pla-util eth0 discover
c0:06:c3:xx:xx:60 via MII1 interface, HFID: tpver_701F14_191101_901
c0:06:c3:xx:xx:ec via PLC interface, HFID: tpver_701F14_191101_901
c0:06:c3:xx:xx:13 via PLC interface, HFID: tpver_701F14_191101_901

$ pla-util eth0 get-capabilities
AV Version:             2.0
MAC Address:            c0:06:c3:xx:xx:60
OUI:                    001f84
Backup CCo:             CAPABLE
Proxy:                  NOT_CAPABLE
Implementation Version: 1

$ pla-util eth0 get-network-info any
Number of networks: 1
Network 1:
  NID:                             0767ff53596b5e (SL-HS)
  SNID:                            13
  TEI:                             3
  CCo MAC Address:                 c0:06:c3:xx:xx:ec
  Backup CCo MAC Address:          c0:06:c3:xx:xx:60
  Number of Coordinating Networks: 0
  Station Role:                    BACKUP_CCO
  Network Kind:                    IN_HOME_NETWORK
  Status:                          JOINED

$ pla-util eth0 get-id-info
HomePlug AV Version: 2.0
MCS:                 MIMO_NOT_SUPPORTED

$ pla-util eth0 get-network-stats
Error: No response received from adapter
```
Just out of curiosity I tried extending Default_Receive_Timeout to 1000 but to no avail :-(.

**Comment by serock** [comment]
Not good. I'll have to see if I can figure out another way of getting the data rates, but I don't know how long that might take.

**Comment by stn-stn** [comment]
No problem. Let me know if I can help you somehow.

**Comment by serock** [comment]
@stn-stn - I pushed a new implementation of the get-network-stats command. Would you please test it or let me know if you need me to create a new release? Thanks.

**Comment by stn-stn** [comment]
@serock looks much better now, thanks a lot! 

```
$ pla-util eth0 get-network-stats
Number of stations: 2
Station 1:
  Destination Address (DA):  c0:06:c3:xx:xx:13
  Avg PHY Data Rate to DA:   506 Mbps
  Avg PHY Data Rate from DA: 211 Mbps
Station 2:
  Destination Address (DA):  c0:06:c3:xx:xx:ec
  Avg PHY Data Rate to DA:   735 Mbps
  Avg PHY Data Rate from DA: 460 Mbps
```

Now, would it be possible to extend it a bit more? I assume now the speeds are related to the adapter connected to the linux box (c0:06:c3:xx:xx:60). What I would need is to see also the speeds between all the other adapters, e.g. in this case it would be between c0:06:c3:xx:xx:13 and c0:06:c3:xx:xx:ec.

**Comment by RubberDucky007** [comment]
> @serock looks much better now, thanks a lot!
> 
> ```
> $ pla-util eth0 get-network-stats
> Number of stations: 2
> Station 1:
>   Destination Address (DA):  c0:06:c3:xx:xx:13
>   Avg PHY Data Rate to DA:   506 Mbps
>   Avg PHY Data Rate from DA: 211 Mbps
> Station 2:
>   Destination Address (DA):  c0:06:c3:xx:xx:ec
>   Avg PHY Data Rate to DA:   735 Mbps
>   Avg PHY Data Rate from DA: 460 Mbps
> ```
> 
> Now, would it be possible to extend it a bit more? I assume now the speeds are related to the adapter connected to the linux box (c0:06:c3:xx:xx:60). What I would need is to see also the speeds between all the other adapters, e.g. in this case it would be between c0:06:c3:xx:xx:13 and c0:06:c3:xx:xx:ec.

The Ethernet Speed between each PWL-Adapter and a Switch or Host it is connected should be <wirespeed> of the fastest one, or not? So i believed the data rate shown is between the two adapters. Anything else did not make sense to me because the data rate on a linux box could one see with tools ON the box itself.

Am i wrong? All i am interested in is the data rate between my two adapters (no 3. one).

**Comment by RubberDucky007** [comment]
N.B. to say. It worked here.

`./src/pla-util1.1/pla-util enp0s25 get-network-stats
Number of stations: 1
Station 1:
  Destination Address (DA):  c0:25:e9:03:ba:14
  Avg PHY Data Rate to DA:   336 Mbps
  Avg PHY Data Rate from DA: 327 Mbps

./src/pla-util1.1/pla-util enp0s25 get-network-stats
Number of stations: 1
Station 1:
  Destination Address (DA):  c0:25:e9:03:ba:14
  Avg PHY Data Rate to DA:   353 Mbps
  Avg PHY Data Rate from DA: 333 Mbps
`
And i believe the different values from two requests must result from line-conditions on the wire. These values may vary every time. 

Thanks for the Work. This option may help me a lot because i can use it in scripts or crontabs.

**Comment by stn-stn** [comment]
> The Ethernet Speed between each PWL-Adapter and a Switch or Host it is connected should be of the fastest one, or not? So i believed the data rate shown is between the two adapters. Anything else did not make sense to me because the data rate on a linux box could one see with tools ON the box itself.
> 
> Am i wrong? All i am interested in is the data rate between my two adapters (no 3. one).

I'm pretty sure the rates are reported by the PWL adapters themselves. Tools like tpPLC (Win GUI by TP-Link) or plcrate from open-plc-utils are able to show the speeds between all devices on the wire, so technically it is definitely possible, it's probably just a matter of sending proper requests to eacn of the adapters identified by their MAC addresses.

Two adapters is the very basic use case, but for example in my case I have two independent PWL networks connected by ethernet, one has 3 adapters (and it used to be 5 until recently), the other one has now 2 (and it used to be 3). And I'd really love to monitor ther status of the networks and gather the statistics from a single Linux box.

So I'd like to be able to get rates of all the possible mutual PWL connections, i.e.
A -> B 
A <- B
A -> C
A <- C
B -> C
B <- C
X -> Y
X <- Y

@serock Perhaps it might be possible to simply add an optional <MAC address> argument so that the user can explicitly select the adaptetr to communicate with, when getting the network stats? I assume by default is uses the "nearest" one connected by ethernet, right?

**Comment by serock** [comment]
@stn-stn and @RubberDucky007 - thank you both for testing.

@stn-stn - You are correct, the get-network-stats command uses the "nearest" adapter connected by Ethernet. First the command broadcasts a discover request to find adapters and their MAC addresses. Typically, two or more adapters will reply with a confirm message. Then the command sends a network stats request to the adapter that sent the first confirm message received by the linux box. I could try changing the get-network-stats command to accept an optional MAC address of an adapter, kind of like the reset and restart commands.

**Comment by serock** [comment]
@stn-stn - quick question because you mentioned that you have two independent networks ... when you use the "discover" command, do you see all 5 of your adapters (A, B, C, X, and Y)?

**Comment by stn-stn** [comment]
@serock On the linux box I see only the abovementioned three adapters. The other two are in a different house (two houses sharing one wall, but with independent power infrastructure). The PLA networks are connected via an ethernet cable and switch, making it a single ethernet segment. I assume that it might be possible to discover both networks, but it would have to stop relying on the discovered adapter with fastest response and/or it might need a longer timeout for the responses. The adapters in the second house will take longer to respond, of course.

**Comment by serock** [comment]
@stn-stn - I pushed the changes to add an adapter MAC address parameter to the get-network-stats command. Would you please test it and let me know whether it is working for you? Thanks.

**Comment by stn-stn** [comment]
@serock Sorry but it doesn't build for me, perhaps you didn't add all the changes to the commit? Unfortunately I don't even know how to "hello world" in Ada, this looks like a trivial type incompatibility problem but I have no idea how to fix it :/.

```
$ gprbuild -P pla_util.gpr
Compile
   [Ada]          mac_addresses.adb
mac_addresses.adb:101:73: no candidate interpretations match the actuals:
mac_addresses.adb:101:89: expected type "Standard.Character"
mac_addresses.adb:101:89: found type "Standard.String"
mac_addresses.adb:101:89:   ==> in call to "To_Lower" at g-casuti.ads:62
gprbuild: *** compilation phase failed
```

**Comment by serock** [comment]
@stn-stn - That's odd, all of the changes were committed. Anyway, I just pushed a change to use a different implementation of To_Lower.

**Comment by stn-stn** [comment]
@serock That helped, thank you! I can now confirm that I am able to get all the statistic from all three devices from the first house. I do not know the MAC addresses of the two adapters from the second house, and I am not on-site, so I can't try that yet unless I discover them remotely. I tried discovering them using the discover command, but that only again showed the three adapters from the first house.

```
$ pla-util eth0 get-network-stats
Number of stations: 2
Station 1:
  Destination Address (DA):  c0:06:c3:xx:xx:13
  Avg PHY Data Rate to DA:   543 Mbps
  Avg PHY Data Rate from DA: 216 Mbps
Station 2:
  Destination Address (DA):  c0:06:c3:xx:xx:ec
  Avg PHY Data Rate to DA:   605 Mbps
  Avg PHY Data Rate from DA: 466 Mbps

$ pla-util eth0 get-network-stats c0:06:c3:xx:xx:13
Number of stations: 2
Station 1:
  Destination Address (DA):  c0:06:c3:xx:xx:ec
  Avg PHY Data Rate to DA:   421 Mbps
  Avg PHY Data Rate from DA: 489 Mbps
Station 2:
  Destination Address (DA):  c0:06:c3:xx:xx:60
  Avg PHY Data Rate to DA:   216 Mbps
  Avg PHY Data Rate from DA: 543 Mbps

$ pla-util eth0 get-network-stats c0:06:xx:xx:17:ec
Number of stations: 2
Station 1:
  Destination Address (DA):  c0:06:c3:xx:xx:13
  Avg PHY Data Rate to DA:   489 Mbps
  Avg PHY Data Rate from DA: 421 Mbps
Station 2:
  Destination Address (DA):  c0:06:c3:xx:xx:60
  Avg PHY Data Rate to DA:   466 Mbps
  Avg PHY Data Rate from DA: 655 Mbps

$ pla-util eth0 discover
c0:06:c3:xx:xx:60 via MII1 interface, HFID: tpver_701F14_191101_901
c0:06:c3:xx:xx:ec via PLC interface, HFID: tpver_701F14_191101_901
c0:06:c3:xx:xx:13 via PLC interface, HFID: tpver_701F14_191101_901
```

**Comment by serock** [comment]
@stn-stn - I pushed changes to implement a `get-discover-list` command. Like the `get-network-stats` command, it takes an optional MAC address of an adapter as a parameter. If the `get-discover-list` command works with the TL-PA7017, the command _might_ show the adapters (X and Y) in the other network if the request is sent to the CCo in the A-B-C network. The command shows the other adapters (a.k.a stations) and other networks discovered by the adapter. I have only one network, so my adapters did not discover other networks:

```
~/git/pla-util> ./pla-util eno1 get-discover-list
Number of stations: 1
  MAC Address:         c4:12:f5:xx:xx:xx
  TEI:                 9
  Same Network:        YES
  SNID:                10
  CCo:                 YES
  PCo:                 NO
  Backup CCo:          NO
  Signal Level:        -10 dB < SL <= 0 dB
Number of Networks: 0
```

**Comment by stn-stn** [comment]
@serock You're right, it is now able to discover the other network as well, thanks a lot! And I can now confirm that by using the MAC address from the second network in get-network-stats works fine as well.

Many thanks for the quick updates - I have to say that your tool now does all I need for the network monitoring, so I can now stop bothering you :-)).

The two PLC networks can be easily distinguished by the MAC address vendor prefix, the "near" one starts with c0:06:c3, the "far" one starts with 00:31:92

```
$ pla-util eth0 get-discover-list
Number of stations: 2
  MAC Address:         c0:06:c3:xx:xx:13
  TEI:                 31
  Same Network:        YES
  SNID:                13
  CCo:                 NO
  PCo:                 NO
  Backup CCo:          NO
  Signal Level:        -10 dB < SL <= 0 dB
  MAC Address:         c0:06:c3:xx:xx:ec
  TEI:                 2
  Same Network:        YES
  SNID:                13
  CCo:                 YES
  PCo:                 NO
  Backup CCo:          NO
  Signal Level:        -10 dB < SL <= 0 dB
Number of Networks: 0


$ pla-util eth0 get-discover-list c0:06:c3:xx:xx:13
Number of stations: 3
  MAC Address:         c0:06:c3:xx:xx:ec
  TEI:                 2
  Same Network:        YES
  SNID:                13
  CCo:                 YES
  PCo:                 NO
  Backup CCo:          NO
  Signal Level:        -10 dB < SL <= 0 dB
  MAC Address:         00:31:92:xx:xx:67
  TEI:                 25
  Same Network:        NO
  SNID:                0
  CCo:                 NO
  PCo:                 NO
  Backup CCo:          NO
  Signal Level:        -10 dB < SL <= 0 dB
  MAC Address:         c0:06:c3:xx:xx:60
  TEI:                 3
  Same Network:        YES
  SNID:                13
  CCo:                 NO
  PCo:                 NO
  Backup CCo:          YES
  Signal Level:        -10 dB < SL <= 0 dB
Number of Networks: 1
  NID:                 09e25670ff728c (SL-SC)
  SNID:                0
  Coordinating Status: NON_COORDINATING_NETWORK


$ pla-util eth0 get-discover-list c0:06:c3:xx:xx:ec
Number of stations: 4
  MAC Address:         00:31:92:xx:xx:92
  TEI:                 24
  Same Network:        NO
  SNID:                0
  CCo:                 YES
  PCo:                 NO
  Backup CCo:          NO
  Signal Level:        -10 dB < SL <= 0 dB
  MAC Address:         00:31:92:xx:xx:67
  TEI:                 25
  Same Network:        NO
  SNID:                0
  CCo:                 NO
  PCo:                 NO
  Backup CCo:          NO
  Signal Level:        -10 dB < SL <= 0 dB
  MAC Address:         c0:06:c3:xx:xx:13
  TEI:                 31
  Same Network:        YES
  SNID:                13
  CCo:                 NO
  PCo:                 NO
  Backup CCo:          NO
  Signal Level:        -10 dB < SL <= 0 dB
  MAC Address:         c0:06:c3:xx:xx:60
  TEI:                 3
  Same Network:        YES
  SNID:                13
  CCo:                 NO
  PCo:                 NO
  Backup CCo:          YES
  Signal Level:        -10 dB < SL <= 0 dB
Number of Networks: 1
  NID:                 09e25670ff728c (SL-SC)
  SNID:                0
  Coordinating Status: NON_COORDINATING_NETWORK


$ pla-util eth0 get-network-stats
Number of stations: 2
Station 1:
  Destination Address (DA):  c0:06:c3:xx:xx:13
  Avg PHY Data Rate to DA:   479 Mbps
  Avg PHY Data Rate from DA: 221 Mbps
Station 2:
  Destination Address (DA):  c0:06:c3:xx:xx:ec
  Avg PHY Data Rate to DA:   703 Mbps
  Avg PHY Data Rate from DA: 464 Mbps

$ pla-util eth0 get-network-stats c0:06:c3:xx:xx:13
Number of stations: 2
Station 1:
  Destination Address (DA):  c0:06:c3:xx:xx:ec
  Avg PHY Data Rate to DA:   427 Mbps
  Avg PHY Data Rate from DA: 434 Mbps
Station 2:
  Destination Address (DA):  c0:06:c3:xx:xx:60
  Avg PHY Data Rate to DA:   221 Mbps
  Avg PHY Data Rate from DA: 506 Mbps

$ pla-util eth0 get-network-stats c0:06:c3:xx:xx:ec
Number of stations: 2
Station 1:
  Destination Address (DA):  c0:06:c3:xx:xx:13
  Avg PHY Data Rate to DA:   434 Mbps
  Avg PHY Data Rate from DA: 426 Mbps
Station 2:
  Destination Address (DA):  c0:06:c3:xx:xx:60
  Avg PHY Data Rate to DA:   461 Mbps
  Avg PHY Data Rate from DA: 728 Mbps

$ pla-util eth0 get-network-stats 00:31:92:xx:xx:67
Number of stations: 1
Station 1:
  Destination Address (DA):  00:31:92:xx:xx:92
  Avg PHY Data Rate to DA:   256 Mbps
  Avg PHY Data Rate from DA: 332 Mbps

$ pla-util eth0 get-network-stats 00:31:92:xx:xx:92
Number of stations: 1
Station 1:
  Destination Address (DA):  00:31:92:xx:xx:67
  Avg PHY Data Rate to DA:   321 Mbps
  Avg PHY Data Rate from DA: 256 Mbps
```

**Comment by serock** [comment]
@stn-stn - Thank you for testing. I'm glad that it is working for you. I'll release 1.2.0 within a few days.
