### ISSUE TITLE
asking for interface only if needed

### ISSUE THREAD

**Issue by RubberDucky007** [serock/pla-util#8]
Is it possible to eliminate the need to give the interface name on each run? 
Maybe It could discover itself on which interface is an supported adapter.  Or maybe asking for the right interface. But only if there are more than one interfaces.

**Comment by serock** [comment]
I think I can get the utility to use the first non-loopback, up and running interface by default. If the wrong interface is chosen and the command fails, then the user could retry by providing the interface on the command line.

**Comment by serock** [comment]
@RubberDucky007  - A pre-release of `pla-util` 2.0.0 is available. What I mentioned in my previous comment has been implemented in the pre-release. However, please note that the command syntax has changed and that the program now depends on `libpcap`.

**Comment by serock** [comment]
Release 2.0.0 is available.
