### ISSUE TITLE
Release 2.0.0 is available.

### ISSUE THREAD

**Issue by RubberDucky007** [serock/pla-util#9]
Release 2.0.0 is available.

Tried to Compile it with gprbuild but it did not work.
# gprbuild -P pla_util.gpr 
pla_util.gpr:33:23: object directory "obj" not found
cli.gpr:26:09: exec directory "../bin" not found
cli.gpr:34:29: object directory "obj" not found
common.gpr:30:29: object directory "obj" not found
pla.gpr:32:29: object directory "obj" not found
net.gpr:31:29: object directory "obj" not found
gprbuild: "pla_util.gpr" processing failed

I did a git clone and the DIR's are not there. Downloaded as ZIP and the DIRs are not there too. Is this a problem with the tools or with the repo?

#gprbuild --version
GPRBUILD Community 2018 (20180524) (x86_64-pc-linux-gnu)

# gnat --version
GNAT 8.3.0

libpcap version 0.8 (debian 10 amd64)

**Comment by GDCAU** [comment]
For what its worth, im running Debian 10 on a Arm64 machine and it compiled fine using similar version packages to you.

$ gprbuild --version
GPRBUILD Community 2018 (20180524) (aarch64-unknown-linux-gnu)

$ sudo apt list --installed | grep libpcap
libpcap-dev/oldstable,now 1.8.1-6+deb10u1 arm64 [installed]
libpcap0.8-dev/oldstable,now 1.8.1-6+deb10u1 arm64 [installed,automatic]
libpcap0.8/oldstable,now 1.8.1-6+deb10u1 arm64 [installed,automatic]

$ sudo apt list --installed | grep gpr
gprbuild/oldstable,now 2018-6 arm64 [installed]
libgpr18/oldstable,now 2018-6 arm64 [installed,automatic]

My directory structure looks like this:
$ tree
.
├── CHANGELOG.md
├── cli
│   ├── cli.gpr
│   ├── obj
│   │   ├── b__pla_util.adb
│   │   ├── b__pla_util.ads
│   │   ├── b__pla_util.ali
│   │   ├── b__pla_util.o
│   │   ├── commands.adb.stderr
│   │   ├── commands.adb.stdout
│   │   ├── commands.ali
│   │   ├── commands.cswi
│   │   ├── commands.o
│   │   ├── console.adb.stderr
│   │   ├── console.adb.stdout
│   │   ├── console.ali
│   │   ├── console.cswi
│   │   ├── console.o
│   │   ├── pla_util.adb.stderr
│   │   ├── pla_util.adb.stdout
│   │   ├── pla_util.ali
│   │   ├── pla_util.bexch
│   │   ├── pla_util.cswi
│   │   └── pla_util.o
│   └── src
│       ├── commands.adb
│       ├── commands.ads
│       ├── commands-check_dak.adb
│       ├── commands-check_nmk.adb
│       ├── commands-discover.adb
│       ├── commands-get_capabilities.adb
│       ├── commands-get_discover_list.adb
│       ├── commands-get_hfid.adb
│       ├── commands-get_id_info.adb
│       ├── commands-get_network_info.adb
│       ├── commands-get_network_stats.adb
│       ├── commands-reset.adb
│       ├── commands-restart.adb
│       ├── commands-set_hfid.adb
│       ├── commands-set_nmk.adb
│       ├── console.adb
│       ├── console.ads
│       ├── console-process_command_line.adb
│       └── pla_util.adb
├── common
│   ├── common.gpr
│   ├── obj
│   │   ├── config.ads.stderr
│   │   ├── config.ads.stdout
│   │   ├── config.ali
│   │   ├── config.cswi
│   │   ├── config.o
│   │   ├── hfid_strings.ads.stderr
│   │   ├── hfid_strings.ads.stdout
│   │   ├── hfid_strings.ali
│   │   ├── hfid_strings.cswi
│   │   ├── hfid_strings.o
│   │   ├── mac_addresses.adb.stderr
│   │   ├── mac_addresses.adb.stdout
│   │   ├── mac_addresses.ali
│   │   ├── mac_addresses.cswi
│   │   ├── mac_addresses.o
│   │   ├── octets.ads.stderr
│   │   ├── octets.ads.stdout
│   │   ├── octets.ali
│   │   ├── octets.cswi
│   │   └── octets.o
│   └── src
│       ├── config.ads
│       ├── hfid_strings.ads
│       ├── mac_addresses.adb
│       ├── mac_addresses.ads
│       └── octets.ads
├── COPYING
├── cut
├── file.txt
├── LICENSE
├── net
│   ├── net.gpr
│   ├── obj
│   │   ├── packets.adb.stderr
│   │   ├── packets.adb.stdout
│   │   ├── packets.ali
│   │   ├── packets.cswi
│   │   ├── packets-device_locators.adb.stderr
│   │   ├── packets-device_locators.adb.stdout
│   │   ├── packets-device_locators.ali
│   │   ├── packets-device_locators.cswi
│   │   ├── packets-device_locators.o
│   │   ├── packets-filters.adb.stderr
│   │   ├── packets-filters.adb.stdout
│   │   ├── packets-filters.ali
│   │   ├── packets-filters.cswi
│   │   ├── packets-filters.o
│   │   ├── packets-network_devices.adb.stderr
│   │   ├── packets-network_devices.adb.stdout
│   │   ├── packets-network_devices.ali
│   │   ├── packets-network_devices.cswi
│   │   ├── packets-network_devices.o
│   │   ├── packets.o
│   │   ├── packets-pcap.ads.stderr
│   │   ├── packets-pcap.ads.stdout
│   │   ├── packets-pcap.ali
│   │   ├── packets-pcap.cswi
│   │   ├── packets-pcap-devices.ads.stderr
│   │   ├── packets-pcap-devices.ads.stdout
│   │   ├── packets-pcap-devices.ali
│   │   ├── packets-pcap-devices.cswi
│   │   ├── packets-pcap-devices.o
│   │   └── packets-pcap.o
│   └── src
│       ├── os_constants.ads
│       ├── packets.adb
│       ├── packets.ads
│       ├── packets-device_locators.adb
│       ├── packets-device_locators.ads
│       ├── packets-filters.adb
│       ├── packets-filters.ads
│       ├── packets-network_devices.adb
│       ├── packets-network_devices.ads
│       ├── packets-pcap.ads
│       └── packets-pcap-devices.ads
├── obj
├── pla
│   ├── obj
│   │   ├── messages.adb.stderr
│   │   ├── messages.adb.stdout
│   │   ├── messages.ali
│   │   ├── messages-constructors.adb.stderr
│   │   ├── messages-constructors.adb.stdout
│   │   ├── messages-constructors.ali
│   │   ├── messages-constructors.cswi
│   │   ├── messages-constructors.o
│   │   ├── messages.cswi
│   │   ├── messages.o
│   │   ├── power_line_adapters.adb.stderr
│   │   ├── power_line_adapters.adb.stdout
│   │   ├── power_line_adapters.ali
│   │   ├── power_line_adapters-constructors.adb.stderr
│   │   ├── power_line_adapters-constructors.adb.stdout
│   │   ├── power_line_adapters-constructors.ali
│   │   ├── power_line_adapters-constructors.cswi
│   │   ├── power_line_adapters-constructors.o
│   │   ├── power_line_adapters.cswi
│   │   ├── power_line_adapter_sets.ads.stderr
│   │   ├── power_line_adapter_sets.ads.stdout
│   │   ├── power_line_adapter_sets.ali
│   │   ├── power_line_adapter_sets.cswi
│   │   ├── power_line_adapter_sets.o
│   │   ├── power_line_adapters-network.adb.stderr
│   │   ├── power_line_adapters-network.adb.stdout
│   │   ├── power_line_adapters-network.ali
│   │   ├── power_line_adapters-network.cswi
│   │   ├── power_line_adapters-network.o
│   │   └── power_line_adapters.o
│   ├── pla.gpr
│   └── src
│       ├── messages.adb
│       ├── messages.ads
│       ├── messages-constructors.adb
│       ├── messages-constructors.ads
│       ├── power_line_adapters.adb
│       ├── power_line_adapters.ads
│       ├── power_line_adapters-check_dak.adb
│       ├── power_line_adapters-check_nmk.adb
│       ├── power_line_adapters-constructors.adb
│       ├── power_line_adapters-constructors.ads
│       ├── power_line_adapter_sets.ads
│       ├── power_line_adapters-get_any_network_info.adb
│       ├── power_line_adapters-get_capabilities.adb
│       ├── power_line_adapters-get_discover_list.adb
│       ├── power_line_adapters-get_hfid.adb
│       ├── power_line_adapters-get_id_info.adb
│       ├── power_line_adapters-get_manufacturer_hfid.adb
│       ├── power_line_adapters-get_member_network_info.adb
│       ├── power_line_adapters-get_network_info.adb
│       ├── power_line_adapters-get_network_stats.adb
│       ├── power_line_adapters-get_user_hfid.adb
│       ├── power_line_adapters-network.adb
│       ├── power_line_adapters-network.ads
│       ├── power_line_adapters-reset.adb
│       ├── power_line_adapters-restart.adb
│       ├── power_line_adapters-set_hfid.adb
│       └── power_line_adapters-set_nmk.adb
├── pla-util
├── pla_util.gpr
├── README.md
├── run.sh
├── sed
├── shared.gpr
└── uppy.html

13 directories, 178 files

**Comment by serock** [comment]
@RubberDucky007 - My guess is that GPRBUILD Community **2018** isn't creating the directories, although it looks like @glennodotcom used the same GPRBUILD version and it worked. I cloned the project into an empty directory and built it successfully with GPRBUILD Community **2021**, which is still available from [https://www.adacore.com/download](https://www.adacore.com/download). Smaller downloads of GPRBUILD are available under [https://github.com/alire-project/GNAT-FSF-builds/releases](https://github.com/alire-project/GNAT-FSF-builds/releases).

If you don't want to try a newer GPRBUILD, you could download the 2.0.0 source code zip or tar.gz file from [https://github.com/serock/pla-util/releases/tag/2.0.0](https://github.com/serock/pla-util/releases/tag/2.0.0). Those archives should have the directories.

When I started working on this project, I put empty `.gitignore` files into the directories just to make sure that the directories exist. However, after the 2.0.0 release, those files were removed from the git repository because GPRBUILD was creating the directories. I don't know which release of GPRBUILD was the first to create the directories if they were missing.

**Comment by serock** [comment]
@RubberDucky007 - It turns out that if you're using _GPRBUILD Community 2018_, you can add a `-p` option to the first invocation of the gprbuild command after cloning the repo:

`gprbuild -p -P pla_util.gpr`

I've updated the README. Thank you for reporting this issue.
